# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_auto_20170122_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='message',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
